name: Create issue on commit
on:
  push:
    branches:
      - master
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
          with:
            python-version: '3.x'
        - name: Create issue using REST API      
          run: |
            sudo apt install python3-pip
            pip3 install requests
            python ss.py
