name: Create issue on commit
on:
  push:
    branches:
      - master
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@v1
        - name: Create issue using REST API      
          run: |
            ls -a
            python ss.py
