name: launch training job
on:
  push:
    branches:
      - master
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: launch training job      
          run: |
            sudo apt install python-pip
            pip install requests
            python ss.py
